apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-calculator
  name: grpc-calculator-service
spec:
  clusterIP: None
  selector:
    app: grpc-calculator
  ports:
  - name: 6565-tcp
    port: 80
    targetPort: 6565

