apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-client
  labels:
    app: aggregator-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-client
  template:
    metadata:
      labels:
        app: aggregator-client
    spec:
      containers:
        - name: aggregator-client
          image: quay.io/vndube/aggregator-client
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
            - name: grpc.client.square.address
              value: grpc-square-service:80
            - name: rest.square.service.endpoint
              value: rest-square-service:80
